
service: serverless-practice

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  versionFunctions: false

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource:
        - Fn::GetAtt: [OrdersTable, Arn]

custom:
  TABLE_NAME: orders-${self:provider.stage}

functions:
  add-order:
    handler: handler.addOrder
    events:
      - httpApi:
          method: POST
          path: /orders
  
  get-order:
    handler: handler.getOrder
    events:
      - httpApi:
          method: GET
          path: /orders/{id}
resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        Tags:
          - Key: microservice
            Value: orders