
service: serverless-practice

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221


functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          method: POST
          path: /orders

resources:
  Resource:
    dynamodbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - 
            attribute definition
        GlobalSecondaryIndexes:
          - 
            global secondary indexes
        LocalSecondaryIndexes:
          - 
            local secondary indexes
        KeySchema:
          - 
            key schema
        ProvisionedThroughput: 
        TableName: ${self:custom.}
        Tags:
          - Key: microservice
            Value: example